### ISSUE TITLE
Unhandled error at  Load Command

### ISSUE THREAD

**Issue by levlist** [yamaton/h2o-curated-data#3]
Hi,

when I wanted to load a new command and asked the command name, I clicked anywhere outside the input field.
Even the editor or out of VSCode I got the following error message.

![Code_OftK5RwuKP](https://user-images.githubusercontent.com/10905822/158952511-799a6ef4-29de-4522-b39f-51582fb018ce.gif)

**Comment by yamaton** [comment]
I appreciate your report.
I reproduced the bug, fixed it, and released the update as v0.2.2 to the marketplace.
Thanks!
