### ISSUE TITLE
[feat] support adding other languages

### ISSUE THREAD

**Issue by FederAndInk** [yamaton/h2o-curated-data#4]
add support for other languages (other than shellscript) such as [bitbake](https://docs.yoctoproject.org/bitbake/2.4/index.html) (.bb, .bbappend files marked as bitbake lang with the [bitbake extension](https://marketplace.visualstudio.com/items?itemName=microhobby.bitbake2)) which is a mix of python and shell. I think just adding support in the entire bitbake file would be enough.

**Comment by yamaton** [comment]
Thanks for an interesting proposal. 
I'd like to check if the current bash parser (tree-sitter-bash) works okay with bitbake files. Would you suggest me some sample .bb files?

**Comment by yamaton** [comment]
By the way, this repository is for command specs. For VS Code Extension "Shell Script Command Completion", please redirect to https://github.com/yamaton/vscode-h2o . Thanks.

**Comment by FederAndInk** [comment]
That's right, I don't know how I ended up here, sorry
